apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
  namespace: lesson33
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: lesson33
spec:
  selector:
    app: back
  ports:
    - name: back-port
      protocol: TCP
      port: 9002
      targetPort: 8080
