apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: lesson33
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: lesson33
spec:
  selector:
    app: front
  ports:
    - name: front-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: front
  namespace: lesson33
spec:
  podSelector:
    matchLabels:
      app: front
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: back
